#server:
#  port: 8090

#spring.redis:
#  enable: true
#  # Connection URL, will override host, port and password (user will be ignored), e.g. redis://user:password@example.com:6379
#  url: redis://192.168.56.101:6379
#  timeout: 2000 # 连接或读取超时时长（毫秒）
#  database: 7
#  redisson:
#    file: classpath:redisson.yaml
#  jedis:
#    pool:
#      max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
#      max-wait: 800 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-idle: 8 # 连接池中的最大空闲连接
#      min-idle: 2 # 连接池中的最小空闲连接

spring:
  #============== redis ===================
  redis:
    host: 192.168.56.101
    port: 6379
    password: 123456
    redisson:
      file: classpath:redisson.yaml
  rabbitmq:
    host: 192.168.56.101
    port: 5672
    virtual-host: /
    cache:
      channel:
        size: 30
#  ratelimiter:
#    enabled: false
#    sentinel-server: "redis://192.168.56.101:26379,redis://192.168.56.101:26380,redis://192.168.56.101:26381"
#    redis-password: 123456