server:
  port: 9003
#elasticsearch:
#  host: 192.168.56.10
#  port: 9200
logging:
  level:
    com.bawangbai.elastic.search: info
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.56.101:3306/mybatis_plus?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
    url: jdbc:mysql://192.168.200.112:3306/v3testdb_stl?useSSL=false&characterEncoding=utf8
    username: pacypaytest
    password: jf23KEa1=jvnFeXQ
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  elasticsearch:
    rest:
      uris: http://192.168.56.101:9200
      read-timeout: 300S
      connection-timeout: 30S
  rabbitmq:
    host: 192.168.56.101
    port: 5672
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    cache:
      channel:
        size: 30
    listener:
      simple:
        concurrency: 30
        max-concurrency: 30
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 3
          max-interval: 1000
    connection-timeout: 30000
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性
#    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*Mapper.xml