server:
  port: 9001
spring:
  datasource:
    druid:
      initial-size: 5
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 5
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      url: jdbc:mysql://192.168.56.10:3306/mybatis_db?characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      validation-query: select 1
#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
##    url: jdbc:mysql://192.168.56.10:3306/mybatis_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://192.168.56.10:3306/mybatis_db?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    cache-enabled: true
  type-aliases-package: com.bawangbai.mybatis.pojo

logging:
  level:
    com.bawangbai.mybatis: debug